### ISSUE TITLE
Someone copied this library. (This library is real.)

### ISSUE THREAD

**Issue by bedcoding** [spiridonov-oa/react-whiteboard-pdf#11]
I found two libraries that looked identical.
I was very confused because I couldn't tell which of these was real.
https://www.npmjs.com/package/react-whiteboard-pdf
https://www.npmjs.com/package/react-sketch-panel
![스크린샷 2023-09-25 오후 3 28 48](https://github.com/spiridonov-oa/react-whiteboard-pdf/assets/33927558/93c79fbb-c9f2-4aca-b500-a3fa2e587fcb)

Upon checking, some features were missing or an error occurred when downloading the 'react-sketch-panel' project.
![스크린샷 2023-09-25 오후 2 38 46](https://github.com/spiridonov-oa/react-whiteboard-pdf/assets/33927558/4d1c94f3-af01-4d92-93ef-306f36e18e54)
![스크린샷 2023-09-25 오후 2 39 32](https://github.com/spiridonov-oa/react-whiteboard-pdf/assets/33927558/c394956d-9ac7-42af-9625-aa9f42f05221)

Therefore, 'react-whiteboard-pdf' is the original library.
I wrote this down in case there was someone as confused as me.

**Comment by spiridonov-oa** [comment]
Thank you for raising this topic.
