### ISSUE TITLE
What is the difference between 1.2.5 and 1.2.13?

### ISSUE THREAD

**Issue by bedcoding** [spiridonov-oa/react-whiteboard-pdf#16]
The version has been upgraded significantly in the past few days, so I'm curious what the difference is.

**Comment by spiridonov-oa** [comment]
Fixed some bugs and added Tabs for different files

**Comment by bedcoding** [comment]
I understood. When attaching a pdf file, I discovered that several tabs appear.
![스크린샷 2023-11-02 오전 10 08 56](https://github.com/spiridonov-oa/react-whiteboard-pdf/assets/33927558/137bda50-2c31-4faa-85e8-957e22efc07c)

I'm currently developing redo and undo features, and I'm thinking of checking to see if this will have any impact on the new update.

**Comment by spiridonov-oa** [comment]
Oh cool. Thank you so much. You can also make redo and undo using keyboard CMD+Z
